### ISSUE TITLE
Infamous powkiddy a66

### ISSUE THREAD

**Issue by luizsoroca** [shauninman/MinUI#1]
You must know a lot about this device. Sorry if this is on the wrong place. Does this custom firmware works with powkiddy a66 as well? And by the way as from today I assume this last one is a copy... never knew !

**Comment by decojon** [comment]
Yes that works and as far as I know it is just a name change, nothing more.

**Comment by decojon** [comment]
> You must know a lot about this device. Sorry if this is on the wrong place. Does this custom firmware works with powkiddy a66 as well? And by the way as from today I assume this last one is a copy... never knew !

Yes that works and as far as I know it is just a name change, nothing more.
